### ISSUE TITLE
Is it Detected by Antivirus?

### ISSUE THREAD

**Issue by smfai200** [Ekultek/Stitch#2]
Detectable by Antivirus? If So, Any Encoding Sequence to Bypass Antivirus Specially Defender!

**Comment by Ekultek** [comment]
It should not be detectable by any anti-viruses and should be completely FUD. If you for any reason find that it was detected by an anti-virus, please make an issue with the anti-virus type and they payload that was detected. And DO NOT PUT THE PAYLOADS OB VIRUSTOTAL
